version: "3.8"

services:
  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
